### ISSUE TITLE
Feature request: Training without having to type in the solution

### ISSUE THREAD

**Issue by andreassch** [0xpr03/VocableTrainer-Android#12]
On a typical soft-keyboard of a mobile phone, typing in the words is tedious. Thus I suggest an option for an alternative, quicker training method: Just have in your head what you think the solution is, then press a new button labelled check or similar which gives a dialog showing the correct answer and buttons yes and no whether you knew it correctly. Hit the appropriate button and go on with the next word. That way learning is considerably faster.

**Comment by 0xpr03** [comment]
This reminds me a little bit of the game [Concentration](https://en.wikipedia.org/wiki/Concentration_(game)) just with vocables.
What I'm unsure about is the integration of the additional mode into the main UI. Whether it's a new button "non-type mode" (naming?) or a choice box in the settings, I'm not sure.

Note: The yes/no dialog is required & a nice solution to allow for statistics.

**Comment by andreassch** [comment]
If you want to have to separate modes, I suggest to either put it in the settings or ask for the mode at the beginning of a training session. Alternatively, you don't necessarily need another mode, but can also integrate the new button to the existing training mode. Then one can choose for each word whether one wants to enter it with the keyboard to be checked, or do that in ones head and press the check button that presents the correct answer and the yes/no choice.

**Comment by 0xpr03** [comment]
That's an interesting approach, one could argue about the non typing mode being easier to trick than having to type in the solution by yourself to pass, but I think that's over engineering.

**Comment by andreassch** [comment]
Well, I assume that one _wants_ to learn the vocabulary. If you're not honest in answering the yes/no question, you're only cheating yourself. Since that's against your own will to learn, there's no reason to do so.

**Comment by 0xpr03** [comment]
Ok, so I'm currently at implementation stage after having moved around some parts of the trainer. What I'm missing: training mode names. For the current one I'd be okay with "Classic", in terms of the usual mode you would expect. But I can't get a good one for the new mode & would like to use this also for the internal ID.

**Comment by andreassch** [comment]
What about quick mode? Or memory mode?

**Comment by 0xpr03** [comment]
so, I've made the trainer itself pluggable, sadly the classic mode itself looks like this now
I'm not sure whether I want to leave it like that or not
![screenshot_20171115_125524](https://user-images.githubusercontent.com/1280209/32834826-442d875e-ca04-11e7-8107-1267a88ae9eb.png)

**Comment by 0xpr03** [comment]
Ok, so e03e4e62ecfc39eaab18359e2022d2f8c056af16 on dev contains the current preview.

![screenshot_20171118_212843](https://user-images.githubusercontent.com/1280209/32984474-8ecd017c-cca7-11e7-8f05-b7df9b7f8114.png)
![screenshot_20171118_212922](https://user-images.githubusercontent.com/1280209/32984473-8eae9af2-cca7-11e7-9c90-92a34fd4fe62.png)

That would be my GUI idea, if you want some changes tell me.

**Comment by andreassch** [comment]
Looks good.
I have tested it on my phone. The following behaviour is probably a bug: When you start a session, you get a screen with "tTrainerExcercise" and below "tTrainerExColimn" and nothing else. You have to select Classic Mode from the Menu to start training. Selecting Quick Mode does not work before having activated Classic Mode, i.e. you have to select Classic Mode first and then Quick mode.
Moreover, it would be handy if the program remembers the mode I last used.

**Comment by 0xpr03** [comment]
Afaik it should store the selected mode already, both behaviors are definitely 
bugs. You're seeing space holder values, exactly for the purpose of knowing 
that no GUI call has ever happened..
