### ISSUE TITLE
remove trailing whitespace

### ISSUE THREAD

**Issue by ChefKeeper** [0xpr03/VocableTrainer-Android#15]
Maybee we should have a system to clean the superficial spaces, I'm not sure if we can have the same rule for every language, but something like : remove every space before first and last character, and every space following another one (avoid double spacing and more).

This should be done either when creating the list or only when checking the equality.

**Comment by 0xpr03** [comment]
Adding an option for the training mode, to ignore leading/trailing /double spaces could be one thing.
Another one I've first understood, was adding a cleanup option on import / for lists.

**Comment by ChefKeeper** [comment]
Yes that's exactly what I've had in mind, probably first solution is cleaner ?
But is the rule fine for every language ?

**Comment by 0xpr03** [comment]
The option will of course not work for asian Characters like Chinese/Japanese input as afaik you don't have any blank characters there. While I don't know any option similar for those, all Latin based input will profit from it.
(And there's always space for another issue for non latin input improvements.)

**Comment by 0xpr03** [comment]
I've added an option to remove trailing,leading whitespace for input & solution. I'm not sure if you also need removal of double spaces in between, which is why I'm leaving this open.

**Comment by ChefKeeper** [comment]
Hey thank you that's amazing :) !
Maybe removal of double spaces in between would be nice too yes :)

**Comment by 0xpr03** [comment]
I'll add an option for that, but that'll have to wait until #22 is done.

**Comment by 0xpr03** [comment]
Closed in favor of #47 as it already got lost.
