### ISSUE TITLE
one word - multiple translations

### ISSUE THREAD

**Issue by nifker** [0xpr03/VocableTrainer-Android#17]
Can I make a word have multiple translations?

**Comment by 0xpr03** [comment]
Hi, there is currently no native 1:N support, you can just create multiple vocables with the same A word. ( See also [here](https://github.com/0xpr03/VocableTrainer-Android/issues/13#issuecomment-345471823) for some of the problems arising with that approach when trying to de-duplicate. )
TLDR: I would like some support for this, but I don't know how I even would like to ask these in training.
Let's say you can do multiple translations (speaking of the same Language), how would you do the input?
Some of the options:

- Show a multiple-input dialogue for all translations. Expecting each one to be entered.
- Show a hint which one is asked (how?)
- Accept any of the translations.

The current way is dead simple but that's also its power.

I'm calling for an open discussion here as I'm kind of in a dead end on how to approach this.

**Comment by nifker** [comment]
Id say any of the translations should be accepted.

**Comment by 0xpr03** [comment]
Well that'll require a major DB change, so I want some more feedback on this before I throw code at it ;)

**Comment by 0xpr03** [comment]
There's another thing that came up: entry for conjugations which are shown (at the Tip place) on successful solving of the vocable. This can help for verbs.

**Comment by 0xpr03** [comment]
Fixed by #22 
See [Wiki Example](https://github.com/0xpr03/VocableTrainer-Android/wiki/Import#full-example---multilist---multimeaning)
