### ISSUE TITLE
Enhancement: Placeholder for new entries should be the custom column name.

### ISSUE THREAD

**Issue by TobiasMie** [0xpr03/VocableTrainer-Android#18]
When a new list is created the columns get custom names. It whould be nice if this names are displayed in the ```Edit Entry``` dialog instead of the placeholders ```Column A``` and ```Column B```.

![](https://i.imgur.com/jYajZBk.png)

**Comment by 0xpr03** [comment]
Hi, thanks for the report, I'm wondering why that didn't catch my eye.
