### ISSUE TITLE
Enhancement: Disable autocorrection while learning

### ISSUE THREAD

**Issue by TobiasMie** [0xpr03/VocableTrainer-Android#19]
While adding new vocabularies the autocorrection of the keyboard is very useful. While learning the vocabulary it should be disabled so that one has to know the spelling by heart and does not 'sheat' with the autocorrection. This could also be optional.

**Comment by 0xpr03** [comment]
Good catch, do you have a reason to make this optional ?

**Comment by TobiasMie** [comment]
Maybe to make the start easier but it is not really a reason.

**Comment by 0xpr03** [comment]
This should be resolved, I know that there are some old/quirky Android Systems out there that simply ignore this directive. As I've no machine to test this, so I'll keep it this way for now.
