### ISSUE TITLE
Import/Export

### ISSUE THREAD

**Issue by 0xpr03** [0xpr03/VocableTrainer-Android#2]
Currently there is no way a user can import/export his vocables.
What I have in mind is editing vocables from the PC and then importing it into the vocable app, as filling up tables is much easier with a real keyboard.
This could be achieved by using the vocable-trainer for desktop.
Still we would need a import/export strategy like export to SD-Card / work file directory etc.

I'm not sure what's the best solution. Cloud synchronisation would be another option, but I'm not a big fan of it as we would also require some syncing server.

I'm open for ideas.

**Comment by andreassch** [comment]
What about using colon separated values (CSV) ASCII files for import and export? For example, a line in a file for English and German could look like:
eins;one
or, including the column headers (language names)
Deutsch;eins;English;one
CSV files can easily be edited with any text editor. That means one is not limited to type in the vocabulary in in a specific program, and one can import vocabulary lists found on the internet.
Regarding the import/export strategy, I suggest to use an import/export folder in the app's working directory, as this is probably the simplest solution and the user can easily put files there via MTP.

**Comment by 0xpr03** [comment]
> colon separated values (CSV) ASCII files
We'll need to use UTF-8 files, otherwise this could be a nice solution

**Comment by 0xpr03** [comment]
Another thought: Export multiple lists at once or not ?
I think I'll go with special commands that indicate a new list, so we're able to mass ex-/import with one file. If that command is missing we're just assuming one big list. Same goes to list name, column names.

**Comment by andreassch** [comment]
Using UTF8 is a good point.
Regarding multiple data sets, I suggest to use one csv file per list, since the file format (officially) does not support a way to mark the beginning of a new dataset, as far as I know. How would you define such a command so that it will never clash with content?

**Comment by 0xpr03** [comment]
I thought about a line completely filled with something like /;\new_list;/
I don't think this will ever be a vocable.. Even for computer scientists, except sb wants to know this format inside out, and even then we could do an escape. (using //;\\new_list;// or so)

**Comment by 0xpr03** [comment]
little update: I'll implement this in the coming week
my laptop had some hardware issues robbing me of my android simulator

**Comment by 0xpr03** [comment]
Feel free to inspect #3

**Comment by andreassch** [comment]
Sorry for testing so late; I was on vacation.
It would be nice to be able to (manually) choose the column separator. In the CSV files which I already have, a colon is used as column separator, while commas and spaces are used within the columns. At the moment the importer splits these files at spaces, resulting in a mix of both languages in one column and a cut-off entry in the other. It would be great to be able to import the files correctly without having to edit them before.

**Comment by 0xpr03** [comment]
I was hoping for affected people to re-export their Lists via Calc/Excel.
Because atm. I've different ideas about how & how detailed a user defined CSV-Format can / should be and how I integrate this into the GUI. (See [CSVFormat.java](https://github.com/0xpr03/VocableTrainer-Android/blob/master/app/src/main/java/org/apache/commons/csv/CSVFormat.java))

**Comment by andreassch** [comment]
Not sure if I understand you correctly. I take it you are thinking about which settings of CSVFormat shall be selectable by the user via the UI? Following the approach in the CSVFormat class, you could provide a selection between CSV formats, including the predefined ones in the class and an entry "custom". With the latter, all parameters (delimiter, quote character, line separator, etc.) can be individually selected by the user via the UI. These detailed settings might only be shown after selecting "custom" in order not to confuse average users too much.

**Comment by 0xpr03** [comment]
That's also an idea.
I was just thinking about allowing for user defined presets which could be configured in the app settings.
Your approach will be definitely too large for one screen, so I'll have some fun with resizing of the preview view.

**Comment by andreassch** [comment]
Your idea to allow the user to define format presets in the app's settings is better than mine. That way, you don't have to select the details of the format (delimiter, quote mode, line endings, etc.) again when you import several files of the same format. Maybe the import dialog can contain a link to the respective settings (e.g. "create custom format").

**Comment by 0xpr03** [comment]
This could take a while to implement as I'm busy until the end of September.
I'll close this and would suggest you create a new issue with the suggestion. I'm in favour of the custom presets.
