### ISSUE TITLE
N:N Vocables Support

### ISSUE THREAD

**Issue by 0xpr03** [0xpr03/VocableTrainer-Android#22]
This is a tracking issue for N:N vocable support and is subject to change.

- [x] db scheme draft
- [x] user info dialog about upcoming change
- [x] Database implementation
- ~Database upgrade status dialog~
- [x] Database & upgrade testing
- [x] editor integration
- [x] trainer integration
- [x] export support of N:N
- [x] import support of N:N
- [x] export enforce multi-value csv formats
- [X] additional delimiter for multi-value cells required for N:N
- [x] escaping option for delimiter
- [x] additional trainer mode
- [x] update Docs

Preview is in #23 

All questions / feature requests /bugs can be asked/reported here.

**Comment by 0xpr03** [comment]
cc #17 #21 #16

**Comment by 0xpr03** [comment]
One problem I couldn't solve was import/export of N:N vocables in CSV lists.

I can detect 1:N but not N:N in CSV lists.

```csv
A,1
A,2
A,3
B,X
D,X
E,X
```

is detectable as
```
A. 1,2,3
B,D,E : X
```

while I don't know how to express
```
A,B,C : 1,2,3
```

**Comment by 0xpr03** [comment]
#23 Contains the preview, so if you want to test it out and give feedback, check it out.

Currently only DB upgrade & editor is working correctly.

**Comment by daufinsyd** [comment]
Happy to see that there is an issue for N:N vocables support ! :) do you already know how should the word be written in LibreOffice for the export ?

**Comment by 0xpr03** [comment]
Yes, I've added two additional settings to the format section allowing to specify a delimiter for multi-meaning and an escape character for it.
Given escape chare `\`, multi-delimiter `/`
```text
A / B / C,1 / 2 / \/3,MyTip,MyAddition
```
Which is `A,B,C : 1,2,/3` with Tip `MyTip` and addition `MyAddition`

The `Ignore surrounding spaces` option also allows you to write `A / B` instead of `A/B`, trimming the spaces in between.
(See also [here](https://github.com/0xpr03/VocableTrainer-Android/pull/23/files#diff-8471eb36735ae375f676648fd5d77452R18) for some test examples if you're somewhat fluent in java)

![screenshot_20180505_162554](https://user-images.githubusercontent.com/1280209/39664273-11007806-5081-11e8-8e1c-07e4a0cb8c87.png)
![screenshot_20180505_164645](https://user-images.githubusercontent.com/1280209/39664487-ebeb6082-5083-11e8-931b-51ce7109d6c2.png)


The N-N branch already has all of this but lacks the export option as of now. I'm a little busy atm, delaying this feature more then expected. Also I want to test this enough before pushing to production. I'm trying to hunt down a DB upgrade bug which only occurred once but could prevent the app from working.

**Comment by daufinsyd** [comment]
thxs :)

**Comment by 0xpr03** [comment]
Ok, here it is:

 0.6 developer preview. The password is `dev_06` to prevent possible confusion for normal users.
[vocabletrainer-dev.zip](https://github.com/0xpr03/VocableTrainer-Android/files/2068413/vocabletrainer-dev.zip)

**Notice!** To use this preview you'll have to **uninstall your current version** of the app **first**. Otherwise it won't install. The same goes for switching back from this developer version to the f-droid shipped App. Please **backup your Data** via the **export** function!

**Comment by daufinsyd** [comment]
Great :D I'll try it this evening

**Comment by 0xpr03** [comment]
Second preview.
Trainer & Editor are expected to handle viewport changes.
[vocabletrainer-dev.zip](https://github.com/0xpr03/VocableTrainer-Android/files/2132835/vocabletrainer-dev.zip)
