### ISSUE TITLE
Crash on empty Trainingset when resuming.

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [0xpr03/VocableTrainer-Android#24]
#### Expected behavior
On clicking upon resume session it must be resume. 

#### Actual behavior
While clicking on resume session it brings me to home screen. 

#### How to reproduce
Install app from f droid. 

Open it and start session. 

Click on the header to start with an empty session.

Finally it shows you have finished session. 

Then it shows the option in which "resume option " is also present. 

Click on it and it brings us to home. 

* Browser:Vocable Trainer Beta
* Version:0.5.3
* Operating system:5.1.1

#### Recording Of The Bug
https://youtu.be/Tb2443axhnI
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@peerzadazeeshan/app-crashes-while-resuming-the-session">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by 0xpr03** [comment]
Interesting, haven't thought about abusing the header to start with an empty set.

Blocked by #23

**Comment by PeerzadaZeeshan** [comment]
Sir is this post accepted?

**Comment by 0xpr03** [comment]
already fixed in my dev branch, so yeah

it's just obvious that you've not used the app in any way & essentially found a surrogate for starting an invalid session as the button is not clickable except when selecting a list
