### ISSUE TITLE
List is incomplete on landscape orientation

### ISSUE THREAD

**Issue by mcyusuf** [0xpr03/VocableTrainer-Android#27]
#### Expected behavior
The full listview should be visible or be able to display via scrolling up and down the list on both portrait and landscape screen.

#### Actual behavior
On landscape position, three options (delete list, export, import) gets off the list and can't be seen.

#### How to reproduce
Download [here](https://f-droid.org/app/vocabletrainer.heinecke.aron.vocabletrainer), Open app and switch to landscape view on home page.

* App: vocable trainer version 0.5.3
* Operating system: Android Nougat 7.0

#### Recording Of The Bug
![20180330_104349.gif](https://cdn.utopian.io/posts/c9f46a6803c7184dc33dd6da3163e6d5f63020180330_104349.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@mcyusuf/list-is-incomplete-on-landscape-orientation">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by 0xpr03** [comment]
fixed by #23
