### ISSUE TITLE
Dropdown menu for delimiter selection

### ISSUE THREAD

**Issue by OzWT** [0xpr03/VocableTrainer-Android#37]
As discussed in #31 and as desired as a reminder [here](https://github.com/0xpr03/VocableTrainer-Android/issues/31#issuecomment-411445381):
The possibility to select a tab sign directly would be nice. One solution could be a drop-down menu.

Original idea:

> Maybe you can use a drop down menu for delimiters. The custom format settings are much more than only set the delimiter. In most cases, only a few separators are required. And for users who need a special delimiter, one point in the drop down menu could be "other character", which opens the 1 character restricted input window.

**Comment by 0xpr03** [comment]
Here's a mockup, what do you think of it ?
![screenshot_20181005_153346](https://user-images.githubusercontent.com/1280209/46538422-4ad5e380-c8b4-11e8-923a-afcfa50fdd69.png)

**Comment by 0xpr03** [comment]
I'm not sure about the preset of characters.
This will be a general preset, for all character inputs.
@OzWT
