### ISSUE TITLE
add changelog

### ISSUE THREAD

**Issue by leela52452** [0xpr03/VocableTrainer-Android#48]
can you please add changelog.
what is [CHANGELOG](https://en.m.wikipedia.org/wiki/Changelog) ?

**Comment by 0xpr03** [comment]
There is a [changelog](https://github.com/0xpr03/VocableTrainer-Android/tree/master/fastlane/metadata/android/en-US/changelogs) as fastlane format, which is used by f-droid as you can see.

**Comment by leela52452** [comment]
@0xpr03 oh.... i was expecting in a separate file, helps me understand the direction and progress of project over a period of time.
something is better than nothing.

**Comment by 0xpr03** [comment]
I was thinking about that at some point, but I didn't expect many people to look into anything else than what their store provides, if at all. Also there are the git commits, though they're more dense.
I could add a separate changelog if wanted.
