### ISSUE TITLE
File Import broken with recent android API

### ISSUE THREAD

**Issue by 0xpr03** [0xpr03/VocableTrainer-Android#53]
**Describe the bug**
Recent android versions require the use of the [MediaStore.Files](https://developer.android.com/reference/android/provider/MediaStore.Files) system or applying `MANAGE_EXTERNAL_STORAGE` permissions.
The current `WRITE`/`READ_EXTERNAL_STORAGE` permissions won't suffice as they only report media files (images,videos..), since those android changes.

The MediaStore system will apparently replace the file-navigation with some kind of index and removes the folder structure.

The latter one is restricted to a specific set of apps and thus should probably not be used. It may also require additional permissions-requests from the OS, though it works as a drop-in fix for the current system using `appops set --uid vocabletrainer.heinecke.aron.vocabletrainer MANAGE_EXTERNAL_STORAGE allow`.

**To Reproduce**
1. Create an API v30 emulator
2. Drop a .csv file inside
3. Try to import it
4. File isn't visible in file chooser, directory doesn't report this file as existing for the app. File is visible in "Files" App.

**Comment by Bennneeeet** [comment]
Hi @0xpr03 
are there any updates?

**Comment by 0xpr03** [comment]
I'll have to re-do the whole file selection, depending on the android version used, as the "manage external storage" permission won't even work any more on higher android versions. I'm currently implementing the DB 3.0, but I could first try to fix the file stuff.
