### ISSUE TITLE
Support variants of CSV for import/export

### ISSUE THREAD

**Issue by andreassch** [0xpr03/VocableTrainer-Android#6]
Since CSV files come in a variety of flavours, I suggest to let the user select the variant of CSV to use on import, with the possibility to create custom presets in the settings that allow to individually select delimiter, line ending, quote character, quote format, etc. See also discussion on #2.

**Comment by 0xpr03** [comment]
I've pushed my mockup preview to the dev branch. Give me some feedback if you want.
This approach uses just one custom format, which should be enough for almost every use case.
I've exposed all format properties which I'm thinking that they are useful & which are used by the import/export parser.

**Comment by andreassch** [comment]
Thank you for implementing this feature. Now most entries of my files are imported correctly. Can you please also expose the CSVFormat option of a quote character to the UI? That will give full support of the files I have.

**Comment by 0xpr03** [comment]
Please check out the latest update. It should cover your requirements.

**Comment by 0xpr03** [comment]
Note: This could take a little to update as I'm currently breaking huge parts of existing infrastructure to implement the fragment based Settings-View.

**Comment by 0xpr03** [comment]
I've finished rewriting the import-export GUI System to fragments with preferences.
Please test it out and report all remaining bugs. As this is a complete rewrite there can be all types of bugs for the import & export dialog.

**Comment by andreassch** [comment]
Thank you. All worked well in my test. Only the preview is not updated when changing the delimiter character in the custom format.

**Comment by 0xpr03** [comment]
Closed by 99f5e281fea9a032f7d355305e3e660fc6614977
