### ISSUE TITLE
Fixed the blocked texts on the survey page

### ISSUE THREAD

**Issue by EasyVector** [0xpr03/VocableTrainer-Android#61]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the survey page, **the last part of texts and two buttons could not be seen fully, and this page is not scrollable, so there is no way to trigger those buttons or read through this page**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 0.7.3, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that I can see all of the texts and buttons on this survey page, and in this circumstance, part of them seem to be blocked. 

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting
2.open this app for the very first time(never submitted a survey before), and then click "about", then click "close"
3.this error could be seen on the pop-up survey page

**Screenshot**

(The blocked part is indicated in the red box)

<img src="https://user-images.githubusercontent.com/25502419/131091666-f8ca50a9-7c37-49c8-9e79-fcbbe689ece5.png" alt="copy" width="250"/>

**Environment**

1. Version of VocableTrainer: 0.7.3
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by 0xpr03** [comment]
This should be published over the next days on f-droid as 0.7.4 along with some other fixes which took way too long to get working.
Fun fact: I can't actually reproduce this issue with those settings in my emulator, I think it'll depend on your display size & DPI.
![grafik](https://user-images.githubusercontent.com/1280209/132919221-23878275-91d3-4ba7-be6f-aa1a2a718468.png)
