### ISSUE TITLE
Fast Edit from PC

### ISSUE THREAD

**Issue by mawoka-myblock** [0xpr03/VocableTrainer-Android#64]
Hey there, I really love your idea and I would like to contribute, but I am a Java-Noob, so I wanted to ask, if you would need a web-api with webinterface to edit the vocabulary easily from other devices. The stuff I would work with: Python with the framework [FastAPI](https://fastapi.tiangolo.com) and as an interface I'd use [Sevelte](https://svelte.dev) and maybe [Framework7](https://framework7.io).
If I could help, feel free to contact me, if not, then keep up!

**Comment by 0xpr03** [comment]
Hey, just gonna give you a quick braindump for the night so you get a starting point:
The [db 3.0](https://github.com/0xpr03/VocableTrainer-Android/tree/db_3_0) branch includes all the changes I've currently pushed to continue towards online editing, which is basically offline-synchronization against a server, which can then implement editing in the browser. All of that without any mail/password requirements.

I've got the basic idea for the synchronisation inside the [db sheet](https://github.com/0xpr03/VocableTrainer-Android/blob/db_3_0/docs/db%20sheet.ods) for the 3.0 version. What I'm currently planning to do is implementing the backend in rust and anything for the frontend, could be vue, could be react. I've not done anything much in svelte. The reason for that stack is having enough performance, knowledge and experience that it'll run for years without many issues.

Another interesting thing for a new frontend would be [flutter](https://flutter.dev/) as it may also be used as a full client across any OS, if their promises are true and not some UI alien on some systems.. At least for the app I'm currently migrating a ton of stuff towards kotlin, as it's at least a bit better than the java codebase. Which may also give me an easier transition towards a UI refresh. So a ton of stuff that could be done..

**Comment by 0xpr03** [comment]
With that said, what you could do regardless is implement a python version. First of all it'll probably be nice to have more than one implementation, second of all it's open source - do what you want ;) - and third I can focus more on the annoying android code. Also the frontend could still be used for different backends.
I can give you a more detailed description (and in german) regarding my sync protocol idea if you want.

**Comment by mawoka-myblock** [comment]
> With that said, what you could do regardless is implement a python version. First of all it'll probably be nice to have more than one implementation, second of all it's open source - do what you want ;) - and third I can focus more on the annoying android code. Also the frontend could still be used for different backends.
> I can give you a more detailed description (and in german) regarding my sync protocol idea if you want.

The problem: I don't know your API you want to program into the Android-App, so it will be difficult. Would you be fine if I program an API and you would get the OpenAPI-Documentation and integrate that into the Android-App?

**Comment by 0xpr03** [comment]
Well it's always a development process. As I've done a fair amount of brainstorming for the API I'd just give you a direct description of what I had in mind. You could shoot me an email to Ox0p54r36@t-online.de and tell me whether you prefer discord/teamspeak/.. as voice will probably be much faster.
