### ISSUE TITLE
Cannot export data with lineageos 18.1

### ISSUE THREAD

**Issue by tr264** [0xpr03/VocableTrainer-Android#94]
When exporting data, the created file is empty.

 - OS Version lineageos 18.1
 - Application Version 0.82

**Comment by 0xpr03** [comment]
This is tricky as 18.1 is just android 11, which works fine in my tests.
Could you provide a screenshot showing that you a) selected a list to export, and it b) contains data ? (Can be completely made up of demo values.) I'd also like to see the file.

If you want to go a step further, you could try to capture a logcat log file of the export timespan.

**Comment by tr264** [comment]
Sorry for the effort. I retried and it worked. This time I selected the dictionaries to export AFTER specifying the target file name and not before. Maybe there is some improvement potential for user guidance in a way that there is a forced way to fill out the different tabs; or replace tabs with some other GUI feature.

**Comment by 0xpr03** [comment]
> selected the dictionaries to export AFTER specifying the target file name 

Uh, that shouldn't happen.

**Comment by 0xpr03** [comment]
Thanks for the feedback!
